import Foundation

/// [ENCODER-RUNTIME-READY] The bundled resources the internal-testing
/// encoder runtime needs, and the one place they are turned into the
/// objects `AppCoordinator` hands to `IntentEncoderInterpreter`:
///
///  - `Intents/encoder_xlmr_unigram.dat` — the XLM-R 250k Unigram
///    vocabulary + precompiled charsmap the tokenizer runs on
///    (`XlmrUnigramTokenizer`, generated by
///    `tools/train-intent/src/encoder_tokenizer_export.py`);
///  - `Intents/encoder_spike_meta.json` — the label sets, `max_len` and
///    fitted calibration temperature of the pinned artifact
///    (`IntentEncoderManifestResource`).
///
/// ## Failure is UNAVAILABILITY, never an approximation
///
/// If either resource cannot be read, this returns the pair the runtime
/// already has for exactly that situation: `UnavailableIntentEncoderTokenizer`
/// (whose `isReady` is hard false) and the T-033 spike manifest. The
/// interpreter's `isAvailable` is then false, the local-brain chain keeps
/// today's brain, and any direct `interpret()` reports
/// `tokenizer_unavailable` as an observability event. What is deliberately
/// NOT done is substituting labels, ids or a "close enough" vocabulary:
/// the pinned artifact's heads are 12 intents / 13 tags, and decoding them
/// with the 10-intent T-033 label order would silently mislabel utterances.
enum IntentEncoderRuntime {

    /// The two objects the interpreter needs, loaded together so a partial
    /// load (vocabulary present, labels absent, or vice versa) can never
    /// produce a runnable-but-wrong encoder.
    struct Resources {
        let tokenizer: IntentEncoderTokenizing
        let manifest: IntentEncoderManifest
    }

    /// Loads both bundled resources. Never throws: a load failure yields
    /// the explicit UNAVAILABLE pair documented above (the caller is the
    /// gated internal-testing path, and the app must boot either way).
    static func load(bundle: Bundle = .main) -> Resources {
        guard let meta = try? IntentEncoderManifestResource.load(bundle: bundle),
              let tokenizer = try? XlmrUnigramTokenizer.load(bundle: bundle) else {
            return Resources(tokenizer: UnavailableIntentEncoderTokenizer(),
                             manifest: IntentEncoderManifest.t033Spike)
        }
        return Resources(tokenizer: tokenizer, manifest: meta.manifest)
    }
}
