import Foundation
import UIKit

// MARK: - Bundled user manual (user-manual-in-app task)

/// One section of the bundled user manual — the phone-friendly structured
/// content behind Settings → Manuals → "User manual". Ships as a plain
/// JSON bundle resource (`Resources/ManualText/userManual.json`, blue
/// folder reference in project.yml) with one entry per section, BILINGUAL
/// like the device manuals: every section carries its title and
/// paragraphs in BOTH shipped languages (`titleEn`/`titleNe`,
/// `paragraphsEn`/`paragraphsNe`), and the viewer resolves the ACTIVE
/// locale at render time (Nepali content for ne-*, English for everything
/// else — the house fallback). No markdown: bullets are plain paragraphs
/// that start with "• ".
///
/// Visual aids (2026-09-09): sections may declare `images` — programmatic
/// DIAGRAM PNGs (generated by tools/render-manual-images, bilingual,
/// watermarked as sketches, never screenshots) shipped under
/// `ManualText/images/`. The viewer renders the ones that resolve, above
/// the text; images are decorative — a missing image never breaks the
/// section.
struct UserManualSection: Codable, Equatable, Identifiable {
    let id: String
    let titleEn: String
    let titleNe: String
    let paragraphsEn: [String]
    let paragraphsNe: [String]
    /// Diagram file names (e.g. "talk-button-states.png") relative to the
    /// ManualText/images folder. Absent in the JSON decodes as [].
    let images: [String]

    enum CodingKeys: String, CodingKey {
        case id, titleEn, titleNe, paragraphsEn, paragraphsNe, images
    }

    init(id: String, titleEn: String, titleNe: String,
         paragraphsEn: [String], paragraphsNe: [String],
         images: [String] = []) {
        self.id = id
        self.titleEn = titleEn
        self.titleNe = titleNe
        self.paragraphsEn = paragraphsEn
        self.paragraphsNe = paragraphsNe
        self.images = images
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decode(String.self, forKey: .id)
        titleEn = try c.decode(String.self, forKey: .titleEn)
        titleNe = try c.decode(String.self, forKey: .titleNe)
        paragraphsEn = try c.decode([String].self, forKey: .paragraphsEn)
        paragraphsNe = try c.decode([String].self, forKey: .paragraphsNe)
        images = try c.decodeIfPresent([String].self, forKey: .images) ?? []
    }

    /// The section's title in `locale` — Nepali for ne-*, English
    /// otherwise (the unknown-locale fallback). Pure, so the resolution
    /// is pinned by tests without a view.
    func title(locale: Locale) -> String {
        ApplianceLabelLocalizer.isNepali(locale) ? titleNe : titleEn
    }

    /// The section's paragraphs in `locale` — same rule as `title(locale:)`.
    func paragraphs(locale: Locale) -> [String] {
        ApplianceLabelLocalizer.isNepali(locale) ? paragraphsNe : paragraphsEn
    }

    /// True when the section carries usable content in BOTH languages —
    /// a section missing its Nepali translation is invalid, never
    /// silently dropped (the no-missing-translations rule).
    var isValid: Bool {
        guard !id.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return false }
        guard !titleEn.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
              !titleNe.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return false }
        let enOK = paragraphsEn.contains {
            !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        }
        let neOK = paragraphsNe.contains {
            !$0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        }
        return enOK && neOK
    }
}

/// Loads the bundled user-manual sections and their diagram images. The
/// decode seam is injectable (URL/Data → sections; images-folder URL →
/// UIImage) so tests never depend on bundle contents; the shipped
/// artifact gets one honesty test that skips when the resource is absent
/// (the same pattern as `DialectCentroidTable`'s bundled test).
/// Whole-file decode: a malformed payload fails the load loudly (nil)
/// rather than silently dropping sections — the same rule as
/// `BundledManualCatalog.loadManifest`.
enum UserManualCatalog {

    /// Resource file name, without extension.
    static let bundledResourceName = "userManual"

    /// Bundle subdirectory the resource ships in — the project.yml blue
    /// folder reference lands `Resources/ManualText` as `ManualText/` in
    /// the app bundle (JSON at the root, diagrams under `images/`).
    static let bundledSubdirectory = "ManualText"

    /// The shipped resource's URL inside `bundle`, or nil when absent.
    static func bundledURL(bundle: Bundle = .main) -> URL? {
        bundle.url(forResource: bundledResourceName,
                   withExtension: "json",
                   subdirectory: bundledSubdirectory)
    }

    /// Decodes the section list from a JSON file URL.
    static func loadSections(from url: URL) -> [UserManualSection]? {
        guard let data = try? Data(contentsOf: url) else { return nil }
        return loadSections(from: data)
    }

    /// Decodes the section list from raw JSON data.
    static func loadSections(from data: Data) -> [UserManualSection]? {
        try? JSONDecoder().decode([UserManualSection].self, from: data)
    }

    /// The shipped sections, or nil when the resource is absent or
    /// malformed — the viewer shows an honest empty state instead of a
    /// partial manual (constitution: no silent stubs).
    static func bundledSections(bundle: Bundle = .main) -> [UserManualSection]? {
        guard let url = bundledURL(bundle: bundle) else { return nil }
        return loadSections(from: url)
    }

    // MARK: - Diagram images

    /// The diagram image for `name` ("talk-button-states.png") inside the
    /// bundle's ManualText/images folder, or nil when the file is absent
    /// (the viewer then skips the image — decorative-only by contract).
    static func image(named name: String, bundle: Bundle = .main) -> UIImage? {
        guard let folder = bundle.url(forResource: "images",
                                      withExtension: nil,
                                      subdirectory: bundledSubdirectory) else { return nil }
        return image(named: name, imagesFolder: folder)
    }

    /// Pure file-load half of `image(named:bundle:)` — the images folder
    /// is passed in so tests can point it at a temp dir.
    static func image(named name: String, imagesFolder: URL) -> UIImage? {
        UIImage(contentsOfFile: imagesFolder.appendingPathComponent(name).path)
    }
}
