import Foundation
import AVFoundation

/// [TIMER-ALARM] Loud looping bell for the in-app timer alarm — the
/// production `TimerAlarmAudioPlaying`.
///
/// Playback: AVAudioPlayer over the bundled CC0 bell WAV
/// (`Resources/timer-alarm-bell.wav`, generated by
/// `tools/generate-timer-alarm-bell.py`) with `numberOfLoops = -1` — the
/// bell repeats until `stop()`, with NO auto-timeout by design (the single
/// STOP button is the only end of the alarm).
///
/// Audio session (same world as `Speaker.swift` /
/// `AudioSessionManager.swift`): the voice pipeline owns a
/// `.playAndRecord` session. For the duration of the alarm the player
/// switches the shared session to `.playback` + `.defaultToSpeaker` +
/// `.duckOthers`, so the bell
///  - plays even when the phone is on SILENT (unlike the OS notification
///    sound, which respects the silent switch — the foreground alarm is
///    deliberately louder than the background fallback, and that
///    difference is stated in the user-facing copy),
///  - routes to the loudspeaker even with headphones connected
///    (an elderly user may not have them on), and
///  - ducks OTHER apps' audio.
/// On `stop()` the saved category/mode/options are restored IN PLACE (the
/// session is left active — deactivating it would strand the voice
/// pipeline's engine). While the alarm rings the mic is unavailable
/// (`.playback` has no input); that is acceptable — an alarm owns the
/// phone until stopped.
///
/// Honest limits: if the bundled asset is missing (can only happen on a
/// mis-built bundle) the player emits a failure event and stays silent —
/// the full-screen UI still shows the STOP button, and the event makes the
/// defect observable.
final class TimerAlarmBellPlayer: TimerAlarmAudioPlaying {
    private var player: AVAudioPlayer?
    private var savedCategory: AVAudioSession.Category?
    private var savedMode: AVAudioSession.Mode?
    private var savedOptions: AVAudioSession.CategoryOptions?
    private let observabilityBus: ObservabilityBus
    private let bundle: Bundle

    init(observabilityBus: ObservabilityBus, bundle: Bundle = .main) {
        self.observabilityBus = observabilityBus
        self.bundle = bundle
    }

    func startLooping() {
        guard player == nil else { return }  // already ringing
        guard let url = bundle.url(forResource: "timer-alarm-bell",
                                   withExtension: "wav") else {
            emit("timer_alarm_audio_missing_asset", outcome: "failure")
            return
        }
        do {
            let session = AVAudioSession.sharedInstance()
            savedCategory = session.category
            savedMode = session.mode
            savedOptions = session.categoryOptions
            try session.setCategory(.playback, mode: .default,
                                    options: [.duckOthers, .defaultToSpeaker])
            try session.setActive(true)
            let player = try AVAudioPlayer(contentsOf: url)
            player.numberOfLoops = -1  // loop until stop() — no auto-timeout
            player.volume = 1.0
            self.player = player
            player.play()
            emit("timer_alarm_audio_started", outcome: "success")
        } catch {
            emit("timer_alarm_audio_start_failed", outcome: "failure",
                 errorCode: "\((error as NSError).domain)")
            restoreSession()
        }
    }

    func stop() {
        guard player != nil else { return }
        player?.stop()
        player = nil
        restoreSession()
        emit("timer_alarm_audio_stopped", outcome: "success")
    }

    /// Restores the voice pipeline's session configuration in place —
    /// the session stays active, byte-identical category/mode/options.
    private func restoreSession() {
        guard let savedCategory else { return }
        let session = AVAudioSession.sharedInstance()
        try? session.setCategory(savedCategory, mode: savedMode ?? .default,
                                 options: savedOptions ?? [])
        self.savedCategory = nil
        self.savedMode = nil
        self.savedOptions = nil
    }

    private func emit(_ eventType: String, outcome: String,
                      errorCode: String? = nil) {
        observabilityBus.emit(ObservabilityEvent(
            component: "timer_alarm",
            eventType: eventType,
            durationMs: nil,
            outcome: outcome,
            errorCode: errorCode,
            metadata: [:]
        ))
    }
}
