import XCTest
@testable import ElderlyAssistant

/// [ENCODER-RUNTIME-READY] HARD GATE for the Swift XLM-R tokenizer.
///
/// `XlmrUnigramTokenizer` must reproduce the PYTHON tokenizer's output
/// EXACTLY. The Python side (`transformers.AutoTokenizer` on the pinned
/// XLM-R vocabulary, the same call the T-036 training code makes:
/// `tok(words, is_split_into_words=True, add_special_tokens=True,
/// truncation=True, max_length=64)`) is the source of truth; the golden rows
/// were generated by
/// `tools/train-intent/src/encoder_tokenizer_fixtures.py` and every row was
/// re-validated against the committed Python reference
/// (`tools/train-intent/src/xlmr_unigram_ref.py`) before it was written.
///
/// Zero tolerance is the point: a tokenizer that is "close" produces
/// different ids, different word alignment, and therefore silently
/// mislabelled spans downstream. A mismatch here is a BLOCKING FINDING — the
/// fix is in the tokenizer, never in the fixtures.
///
/// Fixture provenance (recorded so a regenerated file is a deliberate act):
///  - 387 rows / 4,368 tokens;
///  - stratified sample of `teacher.jsonl` + `noised.jsonl` (25 per register)
///    and ALL of `edge_cases.jsonl`, plus up to 10 digit-bearing rows;
///  - 68 adversarial cases: empty, whitespace-only, single word, 62/63/64/65/
///    80-word inputs, punctuation runs, literal `<s>`/`</s>`/`<mask>`/`<pad>`/
///    `<unk>` text, ZWJ emoji sequences, Devanagari conjuncts + combining
///    marks, control characters (NUL, U+001C), BOM, fullwidth forms, meta
///    space literals, zero-width/word-joiner/soft-hyphen, 300-char words.
final class XlmrUnigramTokenizerTests: XCTestCase {

    /// Pinned fixture identity. A change here means the fixtures were
    /// regenerated and the numbers in this file's provenance comment (and
    /// `specs/T-037-a-notes.md`) must move with them.
    private static let expectedFixtureRows = 387
    private static let expectedFixtureTokens = 4368

    private var tokenizer: XlmrUnigramTokenizer!

    override func setUpWithError() throws {
        try super.setUpWithError()
        // Bundle.main: the test bundle is hosted by the app, so this is the
        // SAME lookup `IntentEncoderRuntime.load()` performs in production.
        tokenizer = try XlmrUnigramTokenizer.load(bundle: .main)
    }

    // MARK: - Fixture plumbing

    private struct GoldenRow: Decodable {
        let id: String
        let source: String
        let transcript: String
        let words: [String]
        let ids: [Int]
        let wordIndices: [Int?]
    }

    private static func loadGoldenRows() throws -> [GoldenRow] {
        let bundle = Bundle(for: XlmrUnigramTokenizerTests.self)
        // A missing fixture file must FAIL the gate, never skip it: the
        // fixtures are part of the test target's resources (project.yml).
        let url = try XCTUnwrap(
            bundle.url(forResource: "encoder_tokenizer_golden",
                       withExtension: "jsonl", subdirectory: "Fixtures"),
            "encoder_tokenizer_golden.jsonl is not in the test bundle")
        let text = try String(contentsOf: url, encoding: .utf8)
        let decoder = JSONDecoder()
        return try text.split(separator: "\n").map { line in
            try decoder.decode(GoldenRow.self, from: Data(line.utf8))
        }
    }

    // MARK: - The hard gate

    /// THE gate. Every fixture row must produce the Python tokenizer's own
    /// ids, word segmentation and word→token alignment, with an all-ones
    /// attention mask and parallel arrays.
    func testEveryGoldenFixtureRowMatchesThePythonTokenizerExactly() throws {
        let rows = try Self.loadGoldenRows()
        XCTAssertEqual(rows.count, Self.expectedFixtureRows,
                       "fixture set changed — regenerate deliberately (see the class doc)")

        var idMismatches: [String] = []
        var wordMismatches: [String] = []
        var indexMismatches: [String] = []
        var maskViolations: [String] = []
        var tokenCount = 0

        for row in rows {
            let expectedIDs = row.ids.map(Int32.init)
            guard let encoded = tokenizer.tokenize(sanitisedTranscript: row.transcript,
                                                   maxSequenceLength: 64) else {
                idMismatches.append("\(row.id): tokenizer returned nil")
                continue
            }
            tokenCount += encoded.tokenIds.count
            if encoded.tokenIds != expectedIDs {
                idMismatches.append("\(row.id): expected \(expectedIDs.prefix(16)) "
                                    + "got \(encoded.tokenIds.prefix(16))")
            }
            if encoded.words != row.words {
                wordMismatches.append("\(row.id): expected \(row.words.prefix(8)) "
                                      + "got \(encoded.words.prefix(8))")
            }
            if encoded.wordIndices != row.wordIndices {
                indexMismatches.append("\(row.id): expected \(row.wordIndices.prefix(16)) "
                                       + "got \(encoded.wordIndices.prefix(16))")
            }
            if encoded.attentionMask.contains(where: { $0 != 1 }) {
                maskViolations.append("\(row.id): attention mask is not all ones")
            }
            if encoded.attentionMask.count != encoded.tokenIds.count
                || encoded.wordIndices.count != encoded.tokenIds.count {
                maskViolations.append("\(row.id): parallel arrays are not parallel")
            }
        }

        XCTAssertEqual(idMismatches.count, 0,
                       "ids differ from the Python tokenizer: \(idMismatches.prefix(4))")
        XCTAssertEqual(wordMismatches.count, 0,
                       "word segmentation differs from the Python tokenizer: "
                       + "\(wordMismatches.prefix(4))")
        XCTAssertEqual(indexMismatches.count, 0,
                       "word alignment differs from the Python tokenizer: "
                       + "\(indexMismatches.prefix(4))")
        XCTAssertEqual(maskViolations.count, 0, "\(maskViolations.prefix(4))")
        XCTAssertEqual(tokenCount, Self.expectedFixtureTokens,
                       "total token count changed — regenerate deliberately")
    }

    /// The other half of the alignment contract: the span decoder derives
    /// its own words from the SANITISED transcript
    /// (`IntentEncoderDecoder.wordScalarOffsets`), and abstains unless the
    /// tokenizer's `words` equal that list. Checked on every fixture row,
    /// including the adversarial ones where Python's `str.split()` and
    /// Foundation disagree (U+200B, U+001C..U+001F).
    func testTokenizerWordsEqualTheDecodersOwnSegmentationOnEveryRow() throws {
        let rows = try Self.loadGoldenRows()
        var mismatches: [String] = []
        for row in rows {
            let textWords = IntentEncoderDecoder.wordScalarOffsets(row.transcript)
                .compactMap { IntentEncoderDecoder.scalarSlice(row.transcript,
                                                               start: $0.start,
                                                               end: $0.end) }
            guard let encoded = tokenizer.tokenize(sanitisedTranscript: row.transcript,
                                                   maxSequenceLength: 64) else {
                mismatches.append("\(row.id): tokenizer returned nil")
                continue
            }
            if encoded.words != textWords {
                mismatches.append("\(row.id): decoder \(textWords.prefix(8)) "
                                  + "vs tokenizer \(encoded.words.prefix(8))")
            }
        }
        XCTAssertEqual(mismatches.count, 0,
                       "tokenizer/decoder word disagreement: \(mismatches.prefix(4))")
    }

    // MARK: - Bundled resource

    func testVocabularyResourceIsBundledForTheAppTarget() throws {
        let url = try XCTUnwrap(Bundle.main.url(forResource: XlmrUnigramTokenizer.resourceName,
                                                withExtension: XlmrUnigramTokenizer.resourceExtension,
                                                subdirectory: XlmrUnigramTokenizer.resourceSubdirectory),
                                "Resources/Intents must be a bundled folder reference")
        let size = try FileManager.default
            .attributesOfItem(atPath: url.path)[.size] as? Int
        XCTAssertEqual(size, 5_690_908,
                       "the committed vocabulary table is a pinned resource")
        XCTAssertTrue(tokenizer.isReady)
        XCTAssertEqual(tokenizer.tokenizerID, "xlmr-250k-unigram-v1")
    }

    func testLoadingAMissingOrCorruptResourceFailsExplicitly() throws {
        // Missing file.
        XCTAssertThrowsError(try XlmrUnigramTokenizer.load(
            contentsOf: URL(fileURLWithPath: "/nonexistent/encoder.dat"))) { error in
            guard let loadError = error as? XlmrUnigramTokenizer.LoadError,
                  case .unreadable = loadError else {
                return XCTFail("expected unreadable, got \(error)")
            }
        }
        // Present but not a XLMU0001 resource.
        let garbage = FileManager.default.temporaryDirectory
            .appendingPathComponent("garbage-\(UUID().uuidString).dat")
        try Data("not a vocabulary".utf8).write(to: garbage)
        defer { try? FileManager.default.removeItem(at: garbage) }
        XCTAssertThrowsError(try XlmrUnigramTokenizer.load(contentsOf: garbage)) { error in
            guard let loadError = error as? XlmrUnigramTokenizer.LoadError,
                  case .corrupt = loadError else {
                return XCTFail("expected corrupt, got \(error)")
            }
        }
    }

    /// A resource that lost its tail must be REJECTED, never partially
    /// usable: half a vocabulary would produce plausible-looking ids that
    /// are silently wrong.
    func testTruncatedVocabularyIsRejected() throws {
        let source = try XCTUnwrap(Bundle.main.url(
            forResource: XlmrUnigramTokenizer.resourceName,
            withExtension: XlmrUnigramTokenizer.resourceExtension,
            subdirectory: XlmrUnigramTokenizer.resourceSubdirectory))
        let data = try Data(contentsOf: source)
        let truncated = FileManager.default.temporaryDirectory
            .appendingPathComponent("truncated-\(UUID().uuidString).dat")
        try data.prefix(data.count - 4096).write(to: truncated)
        defer { try? FileManager.default.removeItem(at: truncated) }
        XCTAssertThrowsError(try XlmrUnigramTokenizer.load(contentsOf: truncated)) { error in
            guard case XlmrUnigramTokenizer.LoadError.corrupt = error else {
                return XCTFail("expected corrupt, got \(error)")
            }
        }
    }

    // MARK: - Units

    func testEmptyInputStillGetsTheTemplateTokens() throws {
        let encoded = try XCTUnwrap(tokenizer.tokenize(sanitisedTranscript: "",
                                                       maxSequenceLength: 64))
        XCTAssertEqual(encoded.tokenIds, [0, 2], "<s> </s> only")
        XCTAssertEqual(encoded.attentionMask, [1, 1])
        XCTAssertEqual(encoded.wordIndices, [nil, nil])
        XCTAssertEqual(encoded.words, [])
    }

    func testTruncationReservesBothTemplateTokens() throws {
        let transcript = (0..<100).map { "शब्द\($0)" }.joined(separator: " ")
        let encoded = try XCTUnwrap(tokenizer.tokenize(sanitisedTranscript: transcript,
                                                       maxSequenceLength: 64))
        XCTAssertEqual(encoded.tokenIds.count, 64)
        XCTAssertEqual(encoded.tokenIds.first, 0, "<s> survives truncation")
        XCTAssertEqual(encoded.tokenIds.last, 2, "</s> survives truncation")
        XCTAssertEqual(encoded.attentionMask, [Int32](repeating: 1, count: 64))
        XCTAssertEqual(encoded.wordIndices.count, 64)
    }

    func testMaxSequenceLengthBelowTheTemplateBudgetIsRefused() {
        XCTAssertNil(tokenizer.tokenize(sanitisedTranscript: "नमस्ते",
                                        maxSequenceLength: 1))
    }

    /// U+200B is whitespace to Foundation (and therefore to
    /// `IntentEncoderDecoder.wordScalarOffsets`), even though Unicode says
    /// otherwise. The tokenizer must split exactly as the decoder does —
    /// this is the one boundary where Python's `str.split()` disagrees, so
    /// it is pinned explicitly (adversarial fixture `adv-064`).
    func testZeroWidthSpaceSplitsWordsLikeTheDecoder() throws {
        let transcript = "औषधि\u{200B}खाएँ"
        let encoded = try XCTUnwrap(tokenizer.tokenize(sanitisedTranscript: transcript,
                                                       maxSequenceLength: 64))
        XCTAssertEqual(encoded.words, ["औषधि", "खाएँ"])
        XCTAssertEqual(encoded.wordIndices.compactMap { $0 }.max(), 1)
        XCTAssertEqual(encoded.words,
                       IntentEncoderDecoder.wordScalarOffsets(transcript).compactMap {
                           IntentEncoderDecoder.scalarSlice(transcript,
                                                            start: $0.start,
                                                            end: $0.end)
                       })
    }

    func testMultipleSpacesCollapseToASingleWord() throws {
        let encoded = try XCTUnwrap(tokenizer.tokenize(
            sanitisedTranscript: "औषधि   खाएँ", maxSequenceLength: 64))
        XCTAssertEqual(encoded.words, ["औषधि", "खाएँ"])
    }

    func testAddedTokenTextIsEncodedAsItsIDNotAsPieces() throws {
        let encoded = try XCTUnwrap(tokenizer.tokenize(sanitisedTranscript: "<s>",
                                                       maxSequenceLength: 64))
        XCTAssertEqual(encoded.tokenIds, [0, 0, 2],
                       "the literal <s> is the BOS id, wrapped by the template")
        XCTAssertEqual(encoded.wordIndices, [nil, 0, nil])
    }
}
